# Feature Engineering for Predictive Models

In [54]:
# Case Length
case_length = bpi_challenge_2019.groupby("case_id").size().reset_index(name = "num_events")

In [55]:
# Case Duration
case_durations = bpi_challenge_2019.groupby("case_id")["timestamp"].agg(["min", "max"])

case_durations["duration_hours"] = (case_durations["max"] - case_durations["min"]).dt.total_seconds() / 3600

case_durations = case_durations.reset_index()
case_durations.head()

,case_id,min,max,duration_hours
0,2000000000_00001,2018-01-02 12:53:00+00:00,2018-03-29 13:06:00+00:00,2064.216667
1,2000000001_00001,2018-01-03 08:49:00+00:00,2019-01-17 10:58:00+00:00,9098.150000
2,2000000002_00001,2018-01-04 13:17:00+00:00,2019-01-17 10:59:00+00:00,9069.700000
3,2000000003_00001,2018-01-08 06:21:00+00:00,2018-03-08 12:21:00+00:00,1422.000000
4,2000000003_00002,2018-01-08 06:21:00+00:00,2018-03-08 12:21:00+00:00,1422.000000

In [56]:
# Unique Activities

unique_activities = bpi_challenge_2019.groupby("case_id")["activity"].nunique()

unique_activities = unique_activities.reset_index(name="unique_activities")
unique_activities.head()

            case_id  unique_activities
0  2000000000_00001                 12
1  2000000001_00001                 14
2  2000000002_00001                 15
3  2000000003_00001                 12
4  2000000003_00002                 12

In [84]:
# Resource Count

resource_count = bpi_challenge_2019.groupby("case_id")['resource'].nunique()

resource_count = resource_count.reset_index(name="resource_count")
resource_count.head()

            case_id  resource_count
0  2000000000_00001               5
1  2000000001_00001               6
2  2000000002_00001               5
3  2000000003_00001               5
4  2000000003_00002               5

In [85]:
# Merge Features

features = case_length.merge(case_durations, on="case_id")

features = features.merge(unique_activities, on="case_id")

features = features.merge(resource_count, on="case_id")
features.head()

,case_id,num_events,min,max,duration_hours,target_delay,unique_activities,resource_count
0,2000000000_00001,12,2018-01-02 12:53:00+00:00,2018-03-29 13:06:00+00:00,2064.216667,1,12,5
1,2000000001_00001,15,2018-01-03 08:49:00+00:00,2019-01-17 10:58:00+00:00,9098.150000,1,14,6
2,2000000002_00001,18,2018-01-04 13:17:00+00:00,2019-01-17 10:59:00+00:00,9069.700000,1,15,5
3,2000000003_00001,12,2018-01-08 06:21:00+00:00,2018-03-08 12:21:00+00:00,1422.000000,0,12,5
4,2000000003_00002,12,2018-01-08 06:21:00+00:00,2018-03-08 12:21:00+00:00,1422.000000,0,12,5